# Generated by Django 5.0.6 on 2024-06-25 06:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('data_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('data_create', models.DateTimeField(auto_now=True)),
                ('data_update', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField(default=0.0, verbose_name='Edad')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Salario')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y%m%d')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%Y%m%d')),
                ('categoria', models.ManyToManyField(to='core.categoria', verbose_name='Categoria')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['id'],
            },
        ),
    ]
