# Generated by Django 5.0.6 on 2024-06-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadosmodel',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='empleadosmodel',
            name='type',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='EmpleadosModel',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
