# Generated by Django 5.0.6 on 2024-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadosmodel',
            name='genero',
            field=models.CharField(default=2, max_length=50, verbose_name='Genero'),
            preserve_default=False,
        ),
    ]
