# Generated by Django 5.0.6 on 2024-06-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empleadosmodel_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadosmodel',
            name='genero',
        ),
    ]
