# Generated by Django 5.0.6 on 2024-06-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_type_empleadosmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
        migrations.AddField(
            model_name='empleadosmodel',
            name='categoria',
            field=models.ManyToManyField(to='core.categoria', verbose_name='Categoria'),
        ),
    ]
